# === Configurações do Servidor ===
server.port=8080

# === Conexão com PostgreSQL (LOCAL) ===
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow_db
spring.datasource.username=postgres
spring.datasource.password=senhadobanco
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / Hibernate ===
# Em desenvolvimento: cria/atualiza tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
# Mostra as queries SQL no console (ótimo para aprendizado)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === Logs ===
logging.level.com.joao.taskflow=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# JWT Configuration
jwt.secret=4A6B7C8D9E0F1A2B3C4D5E6F7A8B9C0D1E2F3A4B5C6D7E8F9A0B1C2D3E4F5A6B
jwt.expiration=3600000

springdoc.api-docs.path=/api/docs
springdoc.swagger-ui.path=/api/docs-ui