# === Configurações do Servidor ===
server.port=8080

# === Conexão com PostgreSQL (LOCAL) ===
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow_db
spring.datasource.username=postgres
spring.datasource.password=senhadobanco
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / Hibernate ===
# Em desenvolvimento: cria/atualiza tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
# Mostra as queries SQL no console (ótimo para aprendizado)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === Logs ===
logging.level.com.joao.taskflow=DEBUG
logging.level.org.hibernate.SQL=DEBUG